### ISSUE TITLE
Angie as a known Nginx

### ISSUE THREAD

**Issue by AliML111** [agile6v/awesome-nginx#46]
Could this Nginx based web server be mentioned as a well known distribution or anywhere on the list?
Cause it comes with some great features from Nginx plus out of the box:
 https://github.com/webserver-llc/angie

**Comment by agile6v** [comment]
Great suggestion. Would you be interested in contributing this?
We could put it in *Well-known Distributions*.
Thanks. @AliML111

**Comment by AliML111** [comment]
Thanks for the response,
Of course!
